---
title: "Final Exam"
author: "Prof. Mahdavi"
date: "Spring 2021"
output: html_document
---

TIME LIMITS:
YOU HAVE 24 HOURS TO COMPLETE THIS EXAM.

YOU MUST SUBMIT YOUR CODE AND HTML FILE TO GAUCHOSPACE BY 12:00PM (NOON!) ON TUESDAY JUNE 8th.

RULES:
YOU MAY USE THE INTERNET, TEXTBOOK, AND ANY MATERIAL FROM THE COURSE.
NO EMAIL, PHONE, OR COMMUNICATION WITH ANYONE ABOUT THE EXAM DURING THE 24-HOUR WINDOW.
FAILURE TO FOLLOW THIS RULE LEADS TO A ZERO IN THE COURSE.

PLEASE POST YOUR ANSWERS BELOW EACH QUESTION.

### Part 1. Short answer questions (12 pts total)

Q1. You toss one fair six-sided dice (i.e., one that gives you each number about 1/6th of the time) 10000 times and record the outcome for each roll. If you were to graph a histogram or density plot of all the outcomes, what distribution are you likely to see? Explain why in no more than two sentences. **(4 pts. total)**

**[write your answer here]**


Q2. True or False: Two factors for increasing the size of the standard error of a multivariate OLS coefficient estimate are a small sample size and a high variance inflation factor. Please answer whether this statement is true or false, and explain why in no more than two sentences. **(4 pts. total)**

**[write your answer here]**


Q3. We read an article this quarter by Regina Bateson. (3-4 sentences, 100 words max) **(4 pts. total)**
What is the central research question? *(1 pt.)*
What results does she find? *(1 pt.)*
Are her results robust to alternative model specifications? *(1 pt.)*
Why or why not? *(1 pt.)*

**[write your answers here]**


### Part 2. Racial Flux and Public Opinion (38 pts. total)

How does racial context affect political public opinion? Hamel and Wilcox-Archuleta design a new measure, which they call "racial flux", to answer this question for attitudes towards the 2012 U.S. presidential election. This measure captures how contexts differ between worker and resident populations at the zip code level. They find that higher values of racial flux -- for example, more Black workers relative to Black residents in a zip code -- are associated with more conservative voting behavior and political attitudes based on a large survey of Americans. You will be replicating one aspect of their study, which shows how racial flux correlates with vote intentions for Barack Obama in the 2012 presidential election. 

Load the dataset, `flux.RData`, which you'll find in the Final working directory of the RStudio online platform (and on Gauchospace). Here is a brief description of the variables:

* Year - year of survey response.
* case_id - individual response ID number.
* zipcode - respondent's ZIP code.
* racial_flux - respondent's racial flux score (in percentage units), defined as percentage of Black labor force population minus percentage of Black resident population. 
* pres_dem - dummy variable for whether respondent voted for Obama in the 2012 election (0 = no, 1 = yes)
* pid7 - respondent's self-reported 7-point party identification (1 = strong Democrat, ..., 7 = strong Republican)
* ideo5 - respondent's self-reported ideology (1 = very liberal, ..., 5 = very conservative)
* female - dummy variable for whether respondent identifies as female (0 = no, 1 = yes)
* pct_black - percentage of Black resident population out of total population 

Q4. Set your working directory and load the dataset `flux.RData`. **(2 pts. total)**

**[write your code here]**


Q5. It's always good practice to begin by looking at and summarizing your data. **(5 pts. total)** 
What is your sample size? *(1 pt.)*
What is the mean value of `racial_flux`? *(1 pt.)*
What is the standard deviation of this variable? *(1 pt.)*
What is the unit of analysis here? That is, what does each row in the dataset represent? *(2 pt.)*

**[write your code and answer here]**


Q6. Now let's look at the distribution of this variable. **(5 pts. total)**
Use the `plot(density())` command to plot the distribution. *(1 pt.)*
Interpret the density plot - how could you describe this distribution? *(2 pt.)*
How would you describe the *distribution of the mean* of this distribution? *(2 pt.)*

**[write your code and answer here]**


Q7. Plot the relationship between Black resident population (`pct_black`) and racial flux using a scatterplot. For full credit, you must label all axes in your graph, including the title. **(3 pts. total)**

**[write your code and answer here]**


Q8. Now let's examine the association between `racial_flux` and `pres_dem`. **(4 pts. total)**
What is the covariance of `racial_flux` and `pres_dem`? *(1 pt.)*
What is the correlation? *(1 pt.)*
How would you describe the magnitude of this correlation? *(2 pt.)*

**[write your code and answer here]**


Q9. You want to know whether racial flux (`racial_flux`) predicts vote choice (`pres_dem`), controlling for `female` and `pct_black`. **(4 pts. total)**
In this case, what is your main independent variable? *(1 pt.)* 
What is your dependent variable? *(1 pt.)*
State your null hypothesis. *(1 pt.)* 
State your alternative hypothesis. *(1 pt.)*

**[write your answer here]**


Q10. Run a regression of racial flux on vote choice (`pres_dem`), controlling for female and pct black. **(4 pts. total)**
Show the output of the regression. *(1 pt.)*
Substantively interpret the coefficient that shows the relationship between racial flux and vote choice. *(2 pt.)*
Interpret your p-value. *(1 pt.)*

**[write your code and answer here]**


Q11. Intepret your findings in terms of your hypotheses. Did you find evidence for or against the null hypothesis? **(2 pts. total)**

**[write your answer here]**


Q12. A critic challenges the findings of the study by claiming that the authors did not account for respondent's political preferences. To evaluate their criticism, add the `ideo5` and `pid7` variables to the model you ran in Q10. **(5 pts. total)**
Show the output of this regression. *(1 pt.)*
Interpret the coefficient on the ideology variable (`ideo5`) and evaluate its statistical significance. *(2 pt.)*
Are the model results from Q10 robust to this change? *(1 pt.)*
What kind of bias does this imply for the model in Q10? *(1 pt.)*

**[write your code and answer here]**


Q13. Can you say that we have identified a causal relationship between racial flux and vote choice? Why or why not? **(4 pts. total)**

**[write your answer here]**


Q14. **[BONUS QUESTION]** What is the most interesting and useful idea related to research methods that you learned in this class, which you will remember in the future? *(1 pt.)*

**[write your answer here]**

